//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUID;
	protected global::System.Web.UI.WebControls.Label lblUName;
	protected global::System.Web.UI.WebControls.Label lblUPwd;
	protected global::System.Web.UI.WebControls.Label lblUGender;
	protected global::System.Web.UI.WebControls.Label lblULevel;
	protected global::System.Web.UI.WebControls.Label lblUPhone;
	protected global::System.Web.UI.WebControls.Label lblUEmail;


       
    }
}
