//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Users {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUName;
		protected global::System.Web.UI.WebControls.TextBox txtUPwd;
		protected global::System.Web.UI.WebControls.TextBox txtUGender;
		protected global::System.Web.UI.WebControls.TextBox txtULevel;
		protected global::System.Web.UI.WebControls.TextBox txtUPhone;
		protected global::System.Web.UI.WebControls.TextBox txtUEmail;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
