//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Materials {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMCode;
		protected global::System.Web.UI.WebControls.TextBox txtMName;
		protected global::System.Web.UI.WebControls.TextBox txtMModel;
		protected global::System.Web.UI.WebControls.TextBox txtMMaterial;
		protected global::System.Web.UI.WebControls.TextBox txtMStandard;
		protected global::System.Web.UI.WebControls.TextBox txtMUnit;
		protected global::System.Web.UI.WebControls.TextBox txtMNumber;
		protected global::System.Web.UI.WebControls.TextBox txtWName;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
